There is no exception
Test completed
